urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as django_views

app_name = 'core'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('privacy_policy/', views.privacy, name='privacy'),
]

models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

class Contact(models.Model):
    email = models.CharField(max_length=200)
    message = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.email

forms.py
from django import forms

from .models import *

class ContactForm(forms.ModelForm):


    class Meta:
        model = Contact
        fields = ('email', 'message',)

views.py
from django.shortcuts import render
from django.views import generic
from blog.models import Post
from django.utils import timezone
from .forms import *

from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

class IndexView(generic.ListView):
    template_name = 'core/index.html'
    context_object_name = 'post_list'
    
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        form = ContactForm()
        context.update({
            'form': form,
        })
        return context

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')[:3]
        
    def post(self, request, *args, **kwargs):
        form = ContactForm(request.POST)
        if form.is_valid():
            post = form.save()
        return render(request, 'core/index.html', {
            'form': form,
            'post_list': self.get_queryset()
        })

def privacy(request):
    return render(request, 'core/privacy.html')

templates/core/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

        <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>

        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/device.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'fonts/fontawesome/css/all.min.css' %}">

        <title>Blog</title>
    </head>
    <body>
        <div id="top-scroll"><h3 class="top-scroll none-display">T</h3></div>
        <div class="slide-show" id="slideNone">
            <div class="slide">
                <img src="{% static 'images/Website-Design.jpg' %}" class="img-cover">
                <div class="caption">
                    <h1 class="caption-title">Intrycket Design</h1>
                </div>
            </div>
            {% for post in post_list %}
            <div class="slide">
                <img src="{{ post.image.url }}" class="img-cover">
                <div class="caption">
                    <a href="{% url 'blog:detail' post.id %}">
                        <h1 class="caption-title">{{ post.title }}</h1>
                        <p>{{ post.text|truncatechars:150 }}</p>
                    </a>
                </div>
            </div>
            {% endfor %}
            <div class="dot-box">
                <span class="dot"></span>
                {% for post in post_list %}
                <span class="dot"></span>
                {% endfor %}
            </div>
        </div>
        <div class="nav-bar" id="navbar">
            <a class="nav-item" href="/">Home</a>
            <a class="nav-item" href="{% url 'blog:blog' %}">Blog</a>
            {% if user.is_authenticated %}
                {% if user.is_superuser %}
            <!--<a class="nav-item" href="{ url 'blog:new_post' }">Form</a>-->
            <a class="nav-item" href="{% url 'blog:draft_list' %}">Admin</a>
                {% endif %}
            <a class="nav-item" href="{% url 'user_profile:profile_view' pk=user.pk %}">Profile</a>
            <a class="nav-item" href="{% url 'logout' %}">Log out</a>
            {% else %}
            <a class="nav-item" href="{% url 'login' %}">Log in</a>
            <a class="nav-item" href="{% url 'user_profile:signup' %}">Sign up</a>
            {% endif %}
        </div>

        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
        <div class="footer">
            <a href="https://www.linkedin.com/in/vihan-le-roux-260939175/"><span class="fab fa-linkedin-in footer-icon"></span></a>
            <a href="https://github.com/VihanLeRoux"><span class="fab fa-github footer-icon"></span></a>
            <a href="https://stackoverflow.com/users/9751423/vihan-le-roux"><span class="fab fa-stack-overflow footer-icon"></span></a>
            <a href="https://www.instagram.com/vihanleroux/"><span class="fab fa-instagram footer-icon"></span></a>
            <a href="https://www.facebook.com/vihan.leroux/"><span class="fab fa-facebook-f footer-icon"></span></a>
            <a href="https://www.pinterest.com/nighthowler1275/"><span class="fab fa-pinterest-p footer-icon"></span></a>
            <p>© Copyright 2020 by Intrycket Design</p>
            <a href="{% url 'core:privacy' %}">Privacy Policy</a>
        </div>

        <script src="{% static 'js/base.js' %}"></script>
        <script src="{% static 'js/index.js' %}"></script>
        
    </body>
</html>

templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}
{% load bootstrap4 %}

    {% block content %}
        <div class="row about">
            <div class="col-40">
                <img src="{% static 'images/admin-profile-pic.jpg' %}" class="profile-pic fade"/>
            </div>
            <div class="col-60 about-text">
                <h1>About</h1>
                <p>Hi, my name is Vihan Le Roux. I developed my own startup company, <span class="intrycket">Intrycket Design</span>, to help create an online presence for companies. </p>
                <p>I design and develop intricate websites that are aimed at leaving a lasting impression. I take photos that are meant to amaze and inspire.</p>
                <p>If you are unsure about how to get your business digital or you just want some advice on what to do next, I also do consulting for no extra
                cost. So if you need help with digital marketing, please contact me and I will help.</p>
            </div>
        </div>
        <div class="skills">
            <h1>Skills</h1>
            <p><span class="fas fa-laptop-code"></span> Web development</p>
            <div class="skill-bar fade">
                <div class="skill web">95%</div>
            </div>
            <p><span class="fas fa-camera"></span> Photography</p>
            <div class="skill-bar fade">
                <div class="skill photo">80%</div>
            </div>
            <p><span class="fas fa-bullhorn"></span> Digital marketing</p>
            <div class="skill-bar fade">
                <div class="skill market">60%</div>
            </div>
        </div>
        <div class="parallax"></div>
        <div class="clients">
            <div class="client-item"><span>5+</span>Projects</div>
            <div class="client-item"><span>1+</span>Contracts</div>
            <div class="client-item"><span>2+</span>Consultations</div>
            <div class="client-item"><span>2+</span>Happy Clients</div>
        </div>
        <div class="tech">
            <h1>Technologies</h1>
            <span class="fab fa-html5"></span>
            <span class="fab fa-css3"></span>
            <span class="fab fa-js-square"></span>
            <span class="fab fa-python"></span>
            <span class="fab fa-php"></span>
            <span class="fab fa-linux"></span>
            <span class="fab fa-ubuntu"></span>
            <span class="fab fa-git"></span>
            <span>+15</span>
        </div>
        <div class="gallary">
            <div class="gallary-img-wrap">
                <img src="{% static 'images/stock1.jpg' %}" class="stock">
            </div>
            <div class="gallary-img-wrap">
                <img src="{% static 'images/stock2.jpg' %}" class="stock">
            </div>
            <div class="gallary-img-wrap">
                <img src="{% static 'images/stock3.jpg' %}" class="stock">
            </div>
        </div>
        <div class="contact">
            <h1>Contact</h1>
            <form method="post">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="Submit">
            </form>
        </div>

    {% endblock %}

templates/core/no_carousel.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

        <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>

        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/device.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'fonts/fontawesome/css/all.min.css' %}">
        <title>Blog</title>
    </head>
    <body>
        <div id="top-scroll"><h3 class="top-scroll">T</h3></div>
        <div class="nav-bar fixed" id="navbar">
            <a class="nav-item" href="/">Home</a>
            <a class="nav-item" href="{% url 'blog:blog' %}">Blog</a>
            {% if user.is_authenticated %}
                {% if user.is_superuser %}
            <!--<a class="nav-item" href="{ url 'blog:new_post' }">Form</a>-->
            <a class="nav-item" href="{% url 'blog:draft_list' %}">Admin</a>
                {% endif %}
            <a class="nav-item" href="{% url 'user_profile:profile_view' pk=user.pk %}">Profile</a>
            <a class="nav-item" href="{% url 'logout' %}">Log out</a>
            {% else %}
            <a class="nav-item" href="{% url 'login' %}">Log in</a>
            <a class="nav-item" href="{% url 'user_profile:signup' %}">Sign up</a>
            {% endif %}
        </div>
        </div>

        <div class="container">
            <div class="content">
            {% block content %}
            {% endblock %}
            </div>
        </div>
        <div class="footer">
            <a href="https://www.linkedin.com/in/vihan-le-roux-260939175/"><span class="fab fa-linkedin-in footer-icon"></span></a>
            <a href="https://github.com/VihanLeRoux"><span class="fab fa-github footer-icon"></span></a>
            <a href="https://stackoverflow.com/users/9751423/vihan-le-roux"><span class="fab fa-stack-overflow footer-icon"></span></a>
            <a href="https://www.instagram.com/vihanleroux/"><span class="fab fa-instagram footer-icon"></span></a>
            <a href="https://www.facebook.com/vihan.leroux/"><span class="fab fa-facebook-f footer-icon"></span></a>
            <a href="https://www.pinterest.com/nighthowler1275/"><span class="fab fa-pinterest-p footer-icon"></span></a>
            <p>© Copyright 2020 by Intrycket Design</p>
            <a href="{% url 'core:privacy' %}">Privacy Policy</a>
        </div>
        <script src="{% static 'js/base.js' %}"></script>
        <script src="{% static 'js/profile.js' %}"></script>
    </body>
</html>

templates/core/privacy.html
{% extends 'core/no_carousel.html' %}

    {% block content %}
        <h3>About</h3>
        <p><span class="intrycket">Intrycket Design</span> is an independent website development and design company.</p>
        <h3>Data</h3>
        <p>Your data is by no means sold to other companies. We collect your data when you accept the terms of service when signing up. The data is yours and when you delete 
            your account, we do not keep anything.</p> 
        <p>When you read a blog post, no matter if you have an account or not, a read counter will update the amount of reads on that page. 
            It only adds to the count when you open a post in full view and counting is done by collecting your IP in a session. Once the session has concluded your IP will be removed
            Users with accounts will use there user name when reading to count towards the total. </p>
        <p>A user profile is created when you sign up for an account. These acounts and profiles are completely free. You have access to view your profile and comment. The profile displayes 
            all the comments you might have left on posts.
        </p>
        <p>The links at the bottom redirect you to profiles of Vihan Le Roux. These links are subject to the link website's privacy policy. <span class="intrycket">Intrycket Design</span> 
            will by no means be responsible for your data after that.</p>

    {% endblock %}